### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by CodingMarco** [dabendan2/freenom-dns#5]
Here is what I did:

`pi@raspberrypi:~/git/node/node_modules/.bin $ ./freenom-dns login`
`? email: address@gmail.com`
`? password: ********`
`pi@raspberrypi:~/git/node/node_modules/.bin $ ./freenom-dns list`
`please login first.`

It always says "please login first" even though I entered my email and password correctly!
What am I doing wrong?

**Comment by dabendan2** [comment]
Hi,
  Thanks for your feedback.
  I'll look into it while I have available time.
  Maybe the login method is changed over time.

**Comment by dabendan2** [comment]
Hi CodingMarco,
   Fixed at 0.9.2, please kindly have a try
