### ISSUE TITLE
Login no longer works

### ISSUE THREAD

**Issue by Ayplow** [dabendan2/freenom-dns#6]
The command just asks for the login, then does nothing with it

**Comment by sidpagariya** [comment]
I got that too, is there an easy fix for this?

**Comment by dabendan2** [comment]
Thanks for the feedback.
I'm in vacation now, I'll check it once getting back to computer.
Could you help to enable debug flag and see what happened? please refer to below instructions and set flag to freedom.*
https://www.npmjs.com/package/debug
Any pull request is also appreciated.

**Comment by sidpagariya** [comment]
Hello, after enabling the `DEBUG` flag, here's what I get:
<img width="399" alt="screen shot 2018-02-19 at 9 31 28 pm" src="https://user-images.githubusercontent.com/10685754/36405039-51cf2a08-15bc-11e8-9695-46f30fe56f24.png">

**Comment by dabendan2** [comment]
Hi , login command actually do nothing but store your authentication into local storage for later use.
Does list or any other command output error?

**Comment by sidpagariya** [comment]
Nope, actually I checked the storage and there was nothing in there... Also, it didn't show me any other errors...

**Comment by sidpagariya** [comment]
Also, I have npm version `5.6.0` and node version `9.3.0`.

**Comment by dabendan2** [comment]
Update status
   I've found the behavior change in preferences module which causes the bug.
  However, it seems the login form now require CSRF token while submitting credential.
   It will need some additional work before release new version.

**Comment by sidpagariya** [comment]
Sounds good, thanks!

**Comment by dabendan2** [comment]
Update status
   0.9.3 is released.
   Please kindly have a try.

**Comment by sidpagariya** [comment]
Thanks a lot for the quick fix! It works now!
